---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-ircbd
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: api-ircbd
    spec:
      containers:
      - name: api
        image: {{.API_IMAGE}}
        ports:
          - name: http
            containerPort: 8000
        env:
        - name: DBNAME
          value: "{{.DBNAME}}"
        - name: DBUSER
          value: "{{.DBUSER}}"
        - name: DBPASS
          value: "{{.DBPASS}}"
        - name: DBHOST
          value: "{{.DBHOST}}"
        - name: DBPORT
          value: "{{.DBPORT}}"
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
      - name: keycloak-proxy
        image: quay.io/ukhomeofficedigital/go-keycloak-proxy:v2.0.3
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
          - name: PROXY_ENABLE_CORS_GLOBAL
            value: 'true'
        args:
          - --client-id={{.KEYCLOAK_CLIENT_ID}}
          - --client-secret={{.KEYCLOAK_CLIENT_SECRET}}
          - --listen=127.0.0.1:8081
          - --discovery-url={{.KEYCLOAK_DISCOVERY}}
          - --upstream-url=http://127.0.0.1:8000
          - --json-format
          - --upstream-keepalives
          - --cors-origins=https://{{.WALLBOARD_URL}}
          - --enable-cors-global
          - --resources=uri=/irc_entry|white-listed=true
          - --resources=uri=/health|white-listed=true
          - --resources=uri=/
          - --enable-login-handler
          - --log-requests
          - --verbose
        ports:
          - name: http
            containerPort: 8081