---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    ingress.kubernetes.io/whitelist-source-range: "{{.IP_WHITELIST}}"
  name: api-ircbd-ingress
spec:
  rules:
  - host: {{.API_URL}}
    http:
      paths:
      - backend:
          serviceName: api-ircbd-service
          servicePort: 8081
        path: /
  tls:
  - hosts:
    - {{.API_URL}}
    - www.{{.API_URL}}
    secretName: external-tls