---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: api-ircbd-service
  name: api-ircbd-service
spec:
  ports:
  - name: https
    port: 8081
    targetPort: 8081
  selector:
    name: api-ircbd