---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: api-ircbd-service
  name: api-ircbd-service
spec:
  ports:
  - name: https
    port: 10443
    targetPort: 10443
  selector:
    name: api-ircbd