---
apiVersion: v1
kind: Pod
metadata:
  name: api-schema
spec:
  restartPolicy: Never
  containers:
  - name: api-schema
    image: quay.io/ukhomeofficedigital/removals-api:b2
    args:
      - run
      - migrations
    env:
    - name: LOG_LEVEL
      value: debug
    - name: DBNAME
      value: removals
    - name: DBUSER
      value: root
    - name: DBPASS
      value: {{.DB_PASS}}
    - name: DBHOST
      value: mysql
    - name: DBPORT
      value: "3306"
    resources:
      limits:
        cpu: 250m
        memory: 256Mi