---
apiVersion: v1
kind: Pod
metadata:
  name: api-schema
spec:
  restartPolicy: Never
  containers:
  - name: api-schema
    image: {{.API_IMAGE}}
    args:
      - run
      - migrations
    env:
    - name: LOG_LEVEL
      value: debug
    - name: DBNAME
      value: "{{.DBNAME}}"
    - name: DBUSER
      value: "{{.DBUSER}}"
    - name: DBPASS
      value: "{{.DBPASS}}"
    - name: DBHOST
      value: "{{.DBHOST}}"
    - name: DBPORT
      value: "{{.DBPORT}}"
    resources:
      limits:
        cpu: 250m
        memory: 256Mi