---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: wallboard-ircbd-service
  name: wallboard-ircbd-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    name: wallboard-ircbd